//! Re-exports for protobuf-generated OCO types.
//!
//! The modules below are generated by `tonic-build` / `prost` at compile time.
//! If `protoc` is not installed, stub (empty) modules are emitted instead so
//! that dependent crates still compile.

/// ML service types — embeddings, rerank, health check.
pub mod ml {
    tonic::include_proto!("oco.ml");
}

/// Orchestrator state types — sessions, steps, actions, observations.
pub mod orchestrator {
    tonic::include_proto!("oco.orchestrator");
}
